apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-sbom
spec:
  params:
  - default: https://cyclonedx-bom-repo-server-cyclonedx.apps.cluster-tr47n.tr47n.sandbox987.opentlc.com/
    name: cyclonedxHostUrl
    type: string
  results:
    - description: The url location of the generate SBOM
      name: sbomUrl
  steps:
    - image: 'quay.io/redhat-gpte/syft:0.88.0'
      name: create-sbom
      resources:
        requests:
          memory: 1Gi
      script: >
        syft . --output cyclonedx-xml --source-name globex-ui > ./bom.xml

        curl -X POST $(params.cyclonedxHostUrl)/v1/bom -H "Content-Type: application/vnd.cyclonedx+xml; version=1.4" -H "Accept: */*" -d @bom.xml -D /tmp/header.txt

        LOCATION=$(cat /tmp/header.txt | grep location: | awk '{print $2}' | sed 's|http:|https:|g')

        printf "%s" "$LOCATION" > "$(results.sbomUrl.path)"

        echo "SBOM URL accessible on Results of TaskRun $(context.taskRun.name)"
      workingDir: /workspace/repository
    - image: 'quay.io/redhat-gpte/grype:0.65.2'
      name: scan-sbom
      resources:
        requests:
          memory: 1Gi
      script: >
        set -x

        grype sbom:./bom.xml -o table
      workingDir: /workspace/repository
  workspaces:
  - name: repository
